firstSrt = input()
firstSet = firstSrt.split()
firstSet = set(firstSet)
secondSrt = input()
secondSet = secondSrt.split()
secondSet = set(secondSet)
sdf = firstSet.intersection(secondSet)
sdf = list(sdf)
sdf.sort()
print(*sdf)
